blank_issues_enabled: false
contact_links:
  - name: Accelerate Customer Support
    url: https://support.avaloniaui.net/support
    about: You can create issue on the customer support portal
  - name: Avalonia Community chat on Telegram
    url: https://t.me/Avalonia
    about: Please ask and answer questions here.
  - name: Issues with the Rider extension
    url: https://github.com/ForNeVeR/AvaloniaRider/issues
    about: Create issues specific to the Rider extension in the dedicated repo.
  - name: Issues with the VS Code extension
    url: https://github.com/AvaloniaUI/AvaloniaVSCode/issues
    about: Create issues specific to the VS Code extension in the dedicated repo.
